title: "【図解】ストーリーでわかる！ソフトウェアアーキテクチャ14選"
summary: "主要なソフトウェアアーキテクチャそれぞれを個別の物語形式で学べる本です。カバー画像でイメージを膨らませ、物語の内容に沿ったコードサンプルやクラス図で実際の実装イメージをつかむことができます"
topics: ["ソフトウェアアーキテクチャ","図解","GPT4","ChatGPT","MidJourney"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 0_1_front_matter
  - 0_2_architectures
  - 1_monolithic
  - 2_layered_architecture
  - 3_pipeline_architecture
  - 4_microkernel
  - 5_service_oriented
  - 6_event_driven
  - 7_space-based
  - 8_orchestration_driven
  - 9_microservices
  - 10_modular_monolith
  - 11_serverless
  - 12_clean_architecture
  - 13_onion_architecture
  - closing
  
